paths:
#  - url_path: "/api/candidatures/questions/next/"
#    handler: "handlers.test_gorilla.api_candidatures_questions_next"
#    description: "Test Gorilla Multiple Question Handler"
#    method: "GET"
#    timeout: 5
##    headers:
##      Authorization: "Bearer YOUR_TOKEN"
#
#  - url_path: "firefox/120.0.1/whatsnew/"
#    handler: "handlers.debuggers.debugger_method"
#    description: "Test Gorilla Multiple Question Handler"
#    method: "GET"
#    timeout: 5

  - url_path: "api.hire.toggl.com/graph/candidate"
    handler: "handlers.debuggers.coder_byte"
    description: "Coder Byte Test"
    method: "GET"
    timeout: 5

#  - url_path: "/api/candidatures/test/in_progress/"
#    handler: "handlers.api_candidatures_test_in_progress"
#    description: "Test Gorilla Live Test Handler"
#    method: "POST"
#    retries: 3

drop_paths:
  - "/api/candidatures/anticheating/"
  - "sentry_key="
